version: '3.6'
services:
  elasticsearch:
    container_name: ddev-${DDEV_SITENAME}-elasticsearch
    hostname: ${DDEV_SITENAME}-elasticsearch
    image: elasticsearch:7.17.0
    expose:
      - "9200"
      - "9300"
    environment:
      CLUSTER_NAME: elasticsearch
      DISCOVERY_SERVICE: elasticsearch
      MINIMUM_MASTER_NODES: "1"
      EXPECTED_MASTER_NODES: "1"
      EXPECTED_DATA_NODES: "1"
      RECOVER_AFTER_MASTER_NODES: "1"
      RECOVER_AFTER_DATA_NODES: "1"
      ES_JAVA_OPTS: -Djava.net.preferIPv4Stack=true -Xms512m -Xmx512m
      discovery.type: single-node
    networks: [default, ddev_default]
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ".:/mnt/ddev_config"
  web:
    links:
      - elasticsearch:elasticsearch

volumes:
  elasticsearch: