version: "3.6"

services:
  mysql:
    container_name: ddev-${DDEV_SITENAME}-mysql
    image: mariadb:10.3
    command: --max_allowed_packet=64M
    networks: [default, ddev_default]
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: web
      MYSQL_PASSWORD: web
    expose:
      - 13306:3306
    volumes:
      #- ./services/mysql:/docker-entrypoint-initdb.d:ro,cached
      - ./db:/var/db
      - ".:/mnt/ddev_config"
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
volumes:
  mysql-data: null
