# Schema
danse_moderation_notifications.danse_moderation_notifications.*:
  type: config_entity
  label: 'DanseModerationNotifications'
  mapping:
    id:
      type: string
      label: 'DanseModerationNotifications id'
    uuid:
      type: string
      label: 'UUID'
    group_use:
      type: boolean
      label: 'Group Use'
    group_type:
      type: string
      label: 'Group Type'
    workflow:
      type: string
      label: 'Workflow'
    group_roles:
      type: sequence
      sequence:
        type: string
        label: 'Group roles'
    transitions:
      type: sequence
      sequence:
        type: string
        label: 'Transitions'
    roles:
      type: sequence
      sequence:
        type: string
        label: 'Roles'
    flags:
      type: sequence
      sequence:
        type: string
        label: 'Flags'
    author:
      type: boolean
      label: 'Original Author'
    revision_author:
      type: boolean
      label: 'Revision Author'
    site_mail:
      type: boolean
      label: Disable site mail
    emails:
      type: string
      label: 'Emails'
    subject:
      type: label
      label: 'Subject'
    body:
      type: text_format
      label: 'Email'
    label:
      type: label
      label: 'Label'
    langcode:
      type: string
      label: 'Default language'
    status:
      type: boolean
      label: 'Notification status'
