# The 'type' should be "label" for short meta tags and "label" for ones which
# could get longer, especially ones which use a labelarea field instead of a
# labelfield.

metatag.metatag_tag.epa_title:
  type: label
  label: 'Title'
metatag.metatag_tag.epa_description:
  type: label
  label: 'Description'
metatag.metatag_tag.epa_agency_function:
  type: label
  label: 'Agency Function'
metatag.metatag_tag.epa_audience:
  type: label
  label: 'Audiences'
metatag.metatag_tag.epa_cat:
  type: label
  label: 'Cooperation & Assistance Topics'
metatag.metatag_tag.epa_channel:
  type: label
  label: 'Channel'
metatag.metatag_tag.epa_contenttype:
  type: label
  label: 'Content Type'
metatag.metatag_tag.epa_coverage:
  type: label
  label: 'Geographic Locations'
metatag.metatag_tag.epa_created:
  type: label
  label: 'Date Created'
metatag.metatag_tag.epa_creator:
  type: label
  label: 'Content Creator'
metatag.metatag_tag.epa_ect:
  type: label
  label: 'Emergencies & Cleanup Topics'
metatag.metatag_tag.epa_emt:
  type: label
  label: 'Environmental Media Topics'
metatag.metatag_tag.epa_health:
  type: label
  label: 'Health Topics'
metatag.metatag_tag.epa_industry:
  type: label
  label: 'Industries'
metatag.metatag_tag.epa_language:
  type: label
  label: 'Content language'
metatag.metatag_tag.epa_modified:
  type: label
  label: 'Date Modified'
metatag.metatag_tag.epa_opt:
  type: label
  label: 'Operations Topics'
metatag.metatag_tag.epa_ppt:
  type: label
  label: 'Pollution Prevention Topics'
metatag.metatag_tag.epa_pubnumber:
  type: label
  label: 'Publication Number'
metatag.metatag_tag.epa_rat:
  type: label
  label: 'Research, Analysis & Technology Topics'
metatag.metatag_tag.epa_regulation:
  type: label
  label: 'Environmental Laws, Regulations & Treaties'
metatag.metatag_tag.epa_reviewed:
  type: label
  label: 'Date Reviewed'
metatag.metatag_tag.epa_rit:
  type: label
  label: 'Regulatory & Industrial Topics'
metatag.metatag_tag.epa_substance:
  type: label
  label: 'Substances'
metatag.metatag_tag.epa_type:
  type: label
  label: 'Type'
metatag.metatag_tag.epa_webarea:
  type: label
  label: 'Web Area'
metatag.metatag_tag.epa_webareatype:
  type: label
  label: 'Web Area Type'
